version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_tupachanga_app
    environment:
      POSTGRES_DB: tupachanga
      POSTGRES_USER: oretania
      POSTGRES_PASSWORD: oretania
    ports:
      - "5432:5432"
    volumes:
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql:ro
    restart: always

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: springboot_tupachanga_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tupachanga
      SPRING_DATASOURCE_USERNAME: oretania
      SPRING_DATASOURCE_PASSWORD: oretania
      EMAIL_USERNAME: dani.estudiosdaw@gmail.com
      EMAIL_PASSWORD: vgqf owgn ejkj ennq
    volumes:
      - ../uploads:/app/uploads
    restart: always
